name: Verify Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  verify-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake build-essential git

    - name: Build and Install SDL3
      run: |
        git clone https://github.com/libsdl-org/SDL.git -b main --depth=1
        cd SDL
        mkdir build && cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DSDL_UNIX_CONSOLE_BUILD=ON
        make -j$(nproc)
        sudo make install

    - name: Configure and Build Project
      run: |
        mkdir build && cd build
        cmake .. && make -j$(nproc)

    - name: Verify Executable
      run: |
        if [ -f build/JetRacerDemo ]; then
          echo "✓ Build successful - executable created"
        else
          echo "✗ Build failed - no executable found"
          exit 1
        fi
