name: Verify Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  verify-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install SDL3
      run: sudo apt-get update && sudo apt-get install -y libsdl3-dev

    - name: Configure and Build
      run: |
        mkdir build && cd build
        cmake .. && make -j4

    - name: Verify Executable
      run: |
        if [ -f build/JetRacerDemo ]; then
          echo "✓ Build successful - executable created"
        else
          echo "✗ Build failed - no executable found"
          exit 1
        fi
